name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Check code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest black isort sphinx sphinx_rtd_theme bump2version
    - name: Lint with flake8
      run: |
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check format with black
      run: |
        python -m black --check .
    - name: Check imports with isort
      run: |
        python -m isort --check-only client_code
        python -m isort --check-only server_code
    - name: Run test suite
      run: |
        python -m pytest
    - name: Check docs build
      run: |
        sphinx-build docs build
    - name: Check version numbering
      run: |
        python -m bumpversion --dry-run patch
